### ISSUE TITLE
MVP#1 User Auth

### ISSUE THREAD

**Issue by arpannln** [arpannln/P500X#2]
- [x] No bugs
- [x] User can log in and be redirected 
- [x] user errors are rendered 
- [x] decent styling 
- [x] good enough

**Comment by wongshington** [comment]
- [ ] clear errors when switching from login to signup

**Comment by arpannln** [comment]
I've messed around with the theme a million times, I'll figure it out later lol, fixed everything else tho

**Comment by wongshington** [comment]
- [ ] center your session form within the signup/login box
- [ ] make the "username" and "password" labels a little bit bigger font size and with a little space between those and the input fields
- [ ] the demo and signup/login buttons are too close together
- [ ] the login/demo/signup buttons need a little more space between the text and the borders of the buttons it looks a little cramped currently(potentially making the font bigger on those would also make it easier to read too)
- also im weirdly tied to the errors being rendered in a red font color if you were to keep this color scheme

**Comment by arpannln** [comment]
gucci thanks for the input

**Comment by wongshington** [comment]
- [ ] when you try to login/signup the first time after navigating to your site no errors pop up. you have to click twice for something to happen

**Comment by arpannln** [comment]
Damn good catch

**Comment by wongshington** [comment]
user auth looking mighty fresh my dude
